version: '3.9'

services:
  app:
    image: redis:alpine
    ports:
      - target: 6379
        published: 4690
        protocol: tcp
        mode: host
    volumes:
      - ./redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']