version: '3.8'

services:
    app:
        image: redis:latest
        ports:
            - target: 6379
              published: 4690
              protocol: tcp
              mode: host
        volumes:
            - ./:/redis.conf
        command: ['redis-server', '/redis.conf']
