name: REX Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:
    types:
      - created
jobs:
  build:

    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      with:
          fetch-depth: 0
    - run: git fetch origin develop
    - run: npm i --no-save
    - run: npm run affected:lint --base=remotes/origin/develop
    - run: npm run affected:test --base=remotes/origin/develop
    - run: npm run affected:build --base=remotes/origin/develop
    - run: npm run affected:e2e --base=remotes/origin/develop
      env:
        CI: true