name: REX Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:
    types:
      - created
jobs:
  ci:

    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2   
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: git fetch origin develop
    - run: npm i --no-save
    - run: nx affected --target=lint --base=origin/develop
    - run: nx affected --target=test --base=origin/develop
    - run: nx affected --target=build --base=origin/develop
    - run: nx affected --target=e2e --base=origin/develop
      env:
        CI: true