name: REX Continuous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:
    types:
      - created
jobs:
  build:

    runs-on: [ubuntu-20.04, macos-11.0, windows-2019]

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run affected:lint --base=develop --skip-nx-cache --head=HEAD
    - run: npm run affected:test --base=develop --skip-nx-cache --head=HEAD
    - run: npm run affected:build --base=develop --skip-nx-cache --head=HEAD
    - run: npm run affected:e2e --base=develop --skip-nx-cache --head=HEAD
      env:
        CI: true